//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashHandler.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBalance
    {
        public long CashBalanceID { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Currency { get; set; }
    }
}
