//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashHandler.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long TransactionID { get; set; }
        public double Amount { get; set; }
        public string Denominations { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<long> UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
